image: node:8
stages:
  - test
  - publish

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test

publish:
  stage: publish
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - branches
  script:
    - echo "_auth=$NPM_AUTH" > ~/.npmrc
    - echo "email=$NPM_AUTH_EMAIL" >> ~/.npmrc
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
    - npm publish
